language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - dennys.landy@hotmail.com
services:
- mongodb
script:
#Test unitario y de integracion en perfil DEV, con cobertura
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

# SONARCLOUD PRODUCTOS
- mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=dlandyr-github -Dsonar.login=$USUARIOS

# Deploy
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master